export const PROJECTS = [
  {
    n: "01",
    name: "FFflow",
    tag: "Rust • TUI • FFmpeg",
    desc: "Terminal-based FFmpeg workflow automation tool for professional media engineering.",
    stack: "Rust • Ratatui • Tokio",
    link: "https://github.com/yugaaank/ffflow",
    img: "/ffflow.png",
  },
  {
    n: "02",
    name: "ClearView",
    tag: "Python • AI • Viz",
    desc: "Data clarity and visualization tool for complex datasets.",
    stack: "Python • Streamlit • Pandas",
    link: "https://github.com/yugaaank/clearView",
    img: "/clearView.png",
  },
  {
    n: "03",
    name: "FreshR",
    tag: "Database • Mobile App • React Native",
    desc: "Supabase based react native application for universities/colleges student.",
    stack: "Zustland • React Native • Supabase",
    link: "https://github.com/yugaaank/freshR",
    img: "/interventionGPT.png",
  },
  {
    n: "04",
    name: "AlgoScan",
    tag: "ML • Crypto • Security",
    desc: "Automated cryptographic algorithm identification from raw ciphertext using CatBoost.",
    stack: "Python • Flask • CatBoost • Scikit-learn",
    link: "https://github.com/yugaaank/AlgoScan",
    img: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=2070",
  },
  {
    n: "05",
    name: "Portfolio",
    tag: "Next.js • Portfolio",
    desc: "Personal Portfolio",
    stack: "Vite + React + Motion Framer + Lenis",
    link: "https://github.com/yugaaank/portfolio_v2",
    img: "/v0ra.png",
  },
];
