export const PROJECTS = [
  {
    n: "01",
    name: "FFflow",
    tag: "Rust • TUI • FFmpeg",
    desc: "Terminal-based FFmpeg workflow automation for building clean, modular media pipelines.",
    stack: "Rust • Ratatui • Tokio",
    link: "https://github.com/yugaaank/ffflow",
  },
  {
    n: "02",
    name: "Contx",
    tag: "Python • CLI • AI",
    desc: "Terminal-native context orchestration for injecting relevant state into AI developer workflows.",
    stack: "Python • Typer • LLM",
    link: "https://github.com/yugaaank/contx",
  },
  {
    n: "03",
    name: "Agent Script",
    tag: "Python • AI • Agents",
    desc: "Gemini CLI multi-agent pipeline with specialized agents for product, analysis, architecture, and engineering.",
    stack: "Python • Gemini • Agents",
    link: "https://github.com/yugaaank/agent-script",
  },
  {
    n: "04",
    name: "Dotfiles",
    tag: "Shell • Hyprland • Rice",
    desc: "Minimal, fast, terminal-centric Arch plus Hyprland setup with Neovim, Fish, Kitty, and Starship.",
    stack: "Shell • Nix • Wayland",
    link: "https://github.com/yugaaank/dotfiles",
  },
  {
    n: "05",
    name: "Shy",
    tag: "Rust • Wayland • WM",
    desc: "Auto-hide floating windows for Hyprland: switch to tiled and they vanish, switch back and they are restored.",
    stack: "Rust • Hyprland • IPC",
    link: "https://github.com/yugaaank/shy",
  },
];
