export const PROJECTS = [
  {
    n: "01",
    name: "FFflow",
    tag: "Rust • TUI • FFmpeg",
    desc: "Terminal-based FFmpeg workflow automation tool for professional media engineering.",
    stack: "Rust • Ratatui • Tokio",
    link: "https://github.com/yugankrathore/ffflow",
    img: "/ffflow.png",
  },
  {
    n: "02",
    name: "ClearView",
    tag: "Python • AI • Viz",
    desc: "Data clarity and visualization tool for complex datasets with automated insights.",
    stack: "Python • Streamlit • Pandas",
    link: "https://github.com/yugankrathore/clearView",
    img: "/clearView.png",
  },
  {
    n: "03",
    name: "FreshR",
    tag: "Mobile App • React Native",
    desc: "Supabase based react native application for university and college students.",
    stack: "Zustand • React Native • Supabase",
    link: "https://github.com/yugankrathore/freshR",
    img: "/interventionGPT.png",
  },
  {
    n: "04",
    name: "AlgoScan",
    tag: "ML • Crypto • Security",
    desc: "Automated cryptographic algorithm identification from raw ciphertext using machine learning.",
    stack: "Python • Flask • CatBoost • Scikit-learn",
    link: "https://github.com/yugankrathore/AlgoScan",
    img: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=2070",
  },
  {
    n: "05",
    name: "V0RA",
    tag: "Vite • React • GSAP",
    desc: "Personal portfolio featuring advanced scroll animations and custom shader effects.",
    stack: "React • Lenis • GLSL • CSS",
    link: "https://github.com/yugankrathore/portfolio_v2",
    img: "/v0ra.png",
  },
];
